defaults:
  - model: anthropic #yandex
  - controller: default
  - sage: default
  - context7: default
  - logger: wandb
  - prompt: join_chromatic_pattern #frontiermath_degree19 #transformer
  - system_prompt: v3
  - sage_skill: v2
  - _self_

controller.max_steps: 1

model_name: claude-opus-4-7 #deepseek-v32/latest #gpt-5.5-2026-04-23 #gpt-oss-20b/latest #qwen3:4b-thinking-2507-q4_K_M
mode: chat
progress_logs: true

tools:
  - sage_exec
