defaults:
  - provider: ollama #openai
  - model: qwen3_4b_thinking #openai
  - controller: default
  - sage: default
  - logger: wandb
  - prompt: frontiermath_degree19 #transformer
  - sage_skill: v1
  - _self_

mode: chat
progress_logs: true
tools:
  - sage_exec
